server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  servlet:
    context-path: "/api"
  port: ${NEWS_PORT:8081}

spring:
  application:
    name: news-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/news}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/master.xml
    default-schema: public
    contexts: ${spring.profiles.active:dev} # dev, prod

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${USER_ZIPKIN_URL:http://localhost:9411/api/v2/spans}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

aws:
  s3:
    endpoint: ${NEWS_AWS_S3_HOST:http://localhost:9000}
    singer: AWSS3V3SignerType
    access-key: ${NEWS_AWS_S3_ACCESS_KEY:u4QeDzDwDsK74FzE}
    secret-key: ${NEWS_AWS_S3_SECRET_KEY:Efmm0HwgHfH2lJM0VmdG8ehKaUz2WRNm}
    region: ru-center
    bucket-md: md-bucket
    bucket-html: html-bucket
    bucket-post-photo: post-photo-bucket

springdoc:
  api-docs:
    path: "/api-docs" #api will response on /api-docs
  swagger-ui:
    path: "/swagger-ui.html" # swagger: http://localhost:8080/api/swagger-ui/index.html
    version: "v1"

api:
  logstash:
    url: ${NEWS_LOGSTASH_URL:localhost:5000}
  response-codes:
    ok:
      desc: OK
    badRequest:
      desc: BAD_REQUEST
    notFound:
      desc: NOT_FOUND
